config/routes.rb
Rails.application.routes.draw do
  resources :articles
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "articles#index"

  resources :users, only: [:edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def edit # editのコントローラを作成
    end

    def update # updateのコントローラの作成
        if current_user.update(user_params)
        redirect_to root_path # 編集できたらルートパスに帰る
        else
        render :edit # ユーザーでなかったらeditに戻る
        end
    end

    private

    def user_params
        params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p>
    <strong>Title:</strong>
    <%= article.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= article.content %>
  </p>

</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Articles</h1>

<div id="articles">
  <% @articles.each do |article| %>
    <%= render article %>
    <p>
      <%= link_to "Show this article", article %>
    </p>
  <% end %>
</div>

<%= link_to "New article", new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "一覧に戻る", articles_path %>
</div>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @article %>

<div>
  <%= link_to "Edit this article", edit_article_path(@article) %> |
  <%= link_to "Back to articles", articles_path %>

  <%= button_to "Destroy this article", @article, method: :delete %>
</div>

app/views/layouts/_notifications.html.erb
<div class="notification">
    <%- flash.each do |key, value| %>
        <%= content_tag :div, value, class: key %>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BarsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/notifications'%>
    <%= yield %>
  </body>
</html>

app/views/shared/_side_bar.html.erb
/ ユーザー編集ページに遷移するためのパスを追加
<div class="side-bar">
    <div class="header">
        <% h3.header__name%>
            <%= current_user.name %>
        <% ul.header__lists %>
            <% li.list %>
                <%= link_to do %>
                    <%= icon('fas', 'pensquare', class: 'icon') %>
                <% end %>
    </div>
    <div class="groups">
        <div class="group">
            <div class="group__name">
                グループ名
            </div>
            <div class="group__message">
                新着メッセージ
            </div>
        </div>
        <div class="group">
            <div class="group__name">
                グループ名
            </div>
            <div class="group__message">
                新着メッセージ
            </div>
        </div>
        <div class="group">
            <div class="group__name">
                グループ名
            </div>
            <div class="group__message">
                新着メッセージ
            </div>
        </div>
    </div>
</div>

app/views/users/edit.html.erb
#account-page.account-page  
    <div class="account-page__inner clearfix">
        <div class="account-page__inner--left account-page__header">
            <% h2 Edit Account %>
            <% h5 アカウントの編集 %>
            <%i.btn ログアウト %>
            <%= link_to "トップページに戻る", :back, class: 'btn' %>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn' %>
        </div>
        <div class="account-page__inner--right user-form">
            <%= form_for(current_user) do |f|%>
                <div class="field">
                    <div class="field-label">
                        <%= f.label :name %>
                    </div>
                    <div class="field-input">
                        <%= f.text_field :name, autofocus: true %>
                    </div>
                </div>
                <div class="field">
                    <div class="field-label">
                        <%= f.label :email %>
                    </div>
                    <div class="field-input">
                        <%= f.email_field :email %>
                    </div>
                </div>
                <div class="actions">
                    <%= f.submit "Update", class: 'btn' %>
                </div>
        </div>
    </div>